spring:
  rabbitmq:
    password: ${RABBITMQ_PASSWORD:guest}
    port: '5672'
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USERNAME:guest}
  application:
    name: bff-service
server:
  port: '8004'