name: CI/CD Pipeline

on:
  push:
    branches: [ "lab" ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push BFF
        uses: docker/build-push-action@v5
        with:
          context: ./bff-service
          push: true
          tags: safarislava/pc-api-bff-service:latest

      - name: Build and Push Core
        uses: docker/build-push-action@v5
        with:
          context: ./core-service
          push: true
          tags: safarislava/pc-api-core-service:latest

      - name: Build and Push User
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          push: true
          tags: safarislava/pc-api-user-service:latest

      - name: Build and Push Shot
        uses: docker/build-push-action@v5
        with:
          context: ./shot-service
          push: true
          tags: safarislava/pc-api-shot-service:latest

      - name: Set up Kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to Kubernetes
        env:
          RABBITMQ_PASS: ${{ secrets.RABBITMQ_PASS }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          envsubst < k82-full.yaml | kubectl apply -f -

      - name: Restart Deployments
        run: |
          kubectl rollout restart deployment/api-bff
          kubectl rollout restart deployment/api-core
          kubectl rollout restart deployment/api-user
          kubectl rollout restart deployment/api-shot
